# Generated by Errorkit.
#
# Create an errors table for managing errors.
class CreateErrors < ActiveRecord::Migration
  def self.up
    create_table :errors do |t|
      t.string :environment
      t.string :server
      t.string :version
      t.string :exception
      t.string :message
      t.text   :backtrace
      t.string :controller
      t.string :action
      t.text :session
      t.text :params
      t.string :worker
      t.string :queue
      t.string :payload
      t.string :url
      t.integer :user_id
      t.integer :subject_id
      t.string :subject_type
      t.datetime :resolved_at

      t.timestamps
    end

    add_index :errors, :exception
    add_index :errors, :created_at
    add_index :errors, :resolved_at
  end

  def self.down
    drop_table :errors
  end
end
